routes/web.php
<?php

namespace App\Http\Controllers\Grade;

namespace App\Http\Controllers;

use App\Http\Controllers\Classroom\ClassroomController;
use App\Http\Controllers\Grade\GradeController;
use App\Http\Controllers\Section\SectionController;
use App\Http\Controllers\Student\AttendanceController;
use App\Http\Controllers\Student\FeeController;
use App\Http\Controllers\Student\FeeInvoiceController;
use App\Http\Controllers\Student\GraduatedController;
use App\Http\Controllers\Student\PaymentStudentController;
use App\Http\Controllers\Student\ProcessingFeeController;
use App\Http\Controllers\Student\PromotionController;
use App\Http\Controllers\Student\ReceiptStudentController;
use App\Http\Controllers\Student\StudentController;
use Facade\FlareClient\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['guest']], function () {
    Route::get('/', function () {
        return view('auth.login');
    });
});




Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'auth']
    ],
    function () {

        // Route::get('/', function () {
        //     return view('dashboard');
        // });
        Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');

        Route::resource('grades', GradeController::class);
        //
        Route::resource('classrooms', ClassroomController::class);
        Route::post('delete_all', [ClassroomController::class, 'delete_all'])->name('delete_all');
        Route::post('filter_classes', [ClassroomController::class, 'filter_classes'])->name('filter_classes');
        //
        Route::resource('sections', SectionController::class);
        Route::get('/classes/{id}', [SectionController::class, 'getclasses']);

        //
        Route::view('add_parent', 'livewire.show_form');

        //
        Route::resource('teachers', TeacherController::class);

        //
        Route::resource('students', StudentController::class);

        Route::get('/get_classrooms/{id}', [StudentController::class, 'get_classrooms']);
        Route::get('/get_sections/{id}', [StudentController::class, 'get_sections']);
        Route::post('upload_attachment', [StudentController::class, 'upload_attachment'])->name('upload_attachment');
        Route::get('download_attachment/{studentName}/{fileName}', [StudentController::class, 'download_attachment'])->name('download_attachment');
        Route::post('delete_attachment', [StudentController::class, 'delete_attachment'])->name('delete_attachment');

        Route::resource('promotions', PromotionController::class);
        Route::resource('graduated', GraduatedController::class);
        Route::resource('fees', FeeController::class);
        Route::resource('fees_invoices', FeeInvoiceController::class);
        Route::resource('receipt_students', ReceiptStudentController::class);
        Route::resource('processing_fees', ProcessingFeeController::class);
        Route::resource('payment_students', PaymentStudentController::class);
        Route::resource('attendance', AttendanceController::class );
        Route::resource('subjects', SubjectController::class);


    }
);

        //...

app/Models/Teacher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class Teacher extends Model
{
    use HasFactory;

    use HasTranslations;
    public $translatable = ['name'];
    protected $guarded = [];

    // علاقة بين المعلمين والتخصصات لجلب إسم التخصص
    public function specializations()
    {
        return $this->belongsTo('App\Models\Specialization', 'specialization_id');
    }

    // علاقة بين المعلمين والأنواع لجلب جنس المعلم
    public function genders()
    {
        return $this->belongsTo('App\Models\Gender', 'gender_id');
    }

    public function sections()
    {
        return $this->belongsToMany('App\Models\Section', 'teacher_section');
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTeacher;
use App\Models\Teacher;
use Illuminate\Http\Request;
use App\Repository\TeacherRepositoryInterface;


class TeacherController extends Controller
{
    protected $teacher;

    public function __construct(TeacherRepositoryInterface $teacher)
    {
        $this->teacher = $teacher;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers =  $this->teacher->getAllTeachers();
        return view('teachers.teachers_index', compact('teachers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $specializations = $this->teacher->getSpecialization();
        $genders = $this->teacher->getGender();
        return view('teachers.add_teacher', compact('specializations', 'genders'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTeacher $request)
    {
        return $this->teacher->storeTeacher($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function show(Teacher $teacher)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $teachers = $this->teacher->editTeacher($id);
        $specializations = $this->teacher->Getspecialization();
        $genders = $this->teacher->getGender();
        return view('teachers.edit_teacher', compact('teachers', 'specializations', 'genders'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        return $this->teacher->updateTeacher($request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        return $this->teacher->deleteTeacher($request);
    }
}

resources/views/teachers/add_teacher.blade.php
@extends('layouts.master')
@section('css')
    @toastr_css
@section('title')
    {{ trans('teacher_trans.add_teacher') }}
@stop
@endsection
@section('page-header')
<!-- breadcrumb -->
@section('PageTitle')
    {{ trans('teacher_trans.add_teacher') }}
@stop
<!-- breadcrumb -->
@endsection
@section('content')
<!-- row -->
<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">

                @if (session()->has('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>{{ session()->get('error') }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">


                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
                <div class="col-xs-12">
                    <div class="col-md-12">
                        <br>
                        <form action="{{ route('teachers.store') }}" method="post">
                            @csrf
                            <div class="form-row">
                                <div class="col">
                                    <label for="title">{{ trans('teacher_trans.email') }}</label>
                                    <input type="email" name="email" class="form-control">
                                    @error('email')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col">
                                    <label for="title">{{ trans('teacher_trans.password') }}</label>
                                    <input type="password" name="password" class="form-control">
                                    @error('password')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <br>


                            <div class="form-row">
                                <div class="col">
                                    <label for="title">{{ trans('teacher_trans.name_ar') }}</label>
                                    <input type="text" name="name_ar" class="form-control">
                                    @error('name_ar')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col">
                                    <label for="title">{{ trans('teacher_trans.name_en') }}</label>
                                    <input type="text" name="name_en" class="form-control">
                                    @error('name_en')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <br>
                            <div class="form-row">
                                <div class="form-group col">
                                    <label for="inputCity">{{ trans('teacher_trans.specialization') }}</label>
                                    <select class="custom-select my-1 mr-sm-2" name="specialization_id">
                                        <option selected disabled>{{ trans('parent_trans.choose') }}...</option>
                                        @foreach ($specializations as $specialization)
                                            <option value="{{ $specialization->id }}">{{ $specialization->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('specialization_id')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group col">
                                    <label for="inputState">{{ trans('teacher_trans.gender') }}</label>
                                    <select class="custom-select my-1 mr-sm-2" name="gender_id">
                                        <option selected disabled>{{ trans('Parent_trans.choose') }}...</option>
                                        @foreach ($genders as $gender)
                                            <option value="{{ $gender->id }}">{{ $gender->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('gender_id')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <br>

                            <div class="form-row">
                                <div class="col">
                                    <label for="title">{{ trans('teacher_trans.joining_date') }}</label>
                                    <div class='input-group date'>
                                        <input class="form-control" type="text" id="datepicker-action"
                                            name="joining_date" data-date-format="yyyy-mm-dd" required>
                                    </div>
                                    @error('joining_date')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <br>

                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">{{ trans('teacher_trans.address') }}</label>
                                <textarea class="form-control" name="address" id="exampleFormControlTextarea1"
                                    rows="4"></textarea>
                                @error('address')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <button class="btn btn-success btn-sm nextBtn btn-lg pull-right"
                                type="submit">{{ trans('Parent_trans.next') }}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- row closed -->
@endsection
@section('js')
@toastr_js
@toastr_render
@endsection

resources/views/teachers/edit_teacher.blade.php
@extends('layouts.master')
@section('css')
    @toastr_css
@section('title')
    {{ trans('teacher_trans.edit_teacher') }}
@stop
@endsection
@section('page-header')
<!-- breadcrumb -->
@section('PageTitle')
    {{ trans('teacher_trans.edit_teacher') }}
@stop
<!-- breadcrumb -->
@endsection
@section('content')
<!-- row -->
<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">

                @if (session()->has('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>{{ session()->get('error') }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
                <div class="col-xs-12">
                    <div class="col-md-12">
                        <br>
                        <form action="{{ route('teachers.update', 'test') }}" method="post">
                            {{ method_field('patch') }}
                            @csrf
                            <div class="form-row">
                                <div class="col">
                                    <label for="title">{{ trans('teacher_trans.email') }}</label>
                                    <input type="hidden" value="{{ $teachers->id }}" name="id">
                                    <input type="email" name="email" value="{{ $teachers->email }}"
                                        class="form-control">
                                    @error('email')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col">
                                    <label for="title">{{ trans('teacher_trans.password') }}</label>
                                    <input type="password" name="password" value="{{ $teachers->password }}"
                                        class="form-control">
                                    @error('password')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <br>


                            <div class="form-row">
                                <div class="col">
                                    <label for="title">{{ trans('teacher_trans.name_ar') }}</label>
                                    <input type="text" name="name_ar"
                                        value="{{ $teachers->getTranslation('name', 'ar') }}" class="form-control">
                                    @error('name_ar')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="col">
                                    <label for="title">{{ trans('teacher_trans.name_en') }}</label>
                                    <input type="text" name="name_en"
                                        value="{{ $teachers->getTranslation('name', 'en') }}" class="form-control">
                                    @error('name_en')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <br>
                            <div class="form-row">
                                <div class="form-group col">
                                    <label for="inputCity">{{ trans('teacher_trans.specialization') }}</label>
                                    <select class="custom-select my-1 mr-sm-2" name="specialization_id">
                                        <option value="{{ $teachers->specialization_id }}">
                                            {{ $teachers->specializations->name }}</option>
                                        @foreach ($specializations as $specialization)
                                            <option value="{{ $specialization->id }}">{{ $specialization->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('specialization_id')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group col">
                                    <label for="inputState">{{ trans('teacher_trans.gender') }}</label>
                                    <select class="custom-select my-1 mr-sm-2" name="gender_id">
                                        <option value="{{ $teachers->gender_id }}">{{ $teachers->genders->name }}
                                        </option>
                                        @foreach ($genders as $gender)
                                            <option value="{{ $gender->id }}">{{ $gender->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('gender_id')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <br>

                            <div class="form-row">
                                <div class="col">
                                    <label for="title">{{ trans('teacher_trans.joining_date') }}</label>
                                    <div class='input-group date'>
                                        <input class="form-control" type="text" id="datepicker-action"
                                            value="{{ $teachers->joining_date }}" name="joining_date"
                                            data-date-format="yyyy-mm-dd" required>
                                    </div>
                                    @error('joining_date')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <br>

                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">{{ trans('teacher_trans.address') }}</label>
                                <textarea class="form-control" name="address" id="exampleFormControlTextarea1"
                                    rows="4">{{ $teachers->address }}</textarea>
                                @error('address')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <button class="btn btn-success btn-sm nextBtn btn-lg pull-right"
                                type="submit">{{ trans('parent_trans.next') }}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- row closed -->
@endsection
@section('js')
@toastr_js
@toastr_render
@endsection

resources/views/teachers/teachers_index.blade.php
@extends('layouts.master')
@section('css')
    @toastr_css
@section('title')
    {{ trans('main_trans.teachers_list') }}
@stop
@endsection
@section('page-header')
<!-- breadcrumb -->
@section('PageTitle')
    {{ trans('main_trans.teachers_list') }}
@stop
<!-- breadcrumb -->
@endsection
@section('content')
<!-- row -->
<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">
                <div class="col-xl-12 mb-30">
                    <div class="card card-statistics h-100">
                        <div class="card-body">
                            <a href="{{ route('teachers.create') }}" class="btn btn-success btn-sm" role="button"
                                aria-pressed="true">{{ trans('teacher_trans.add_teacher') }}</a><br><br>
                            <div class="table-responsive">
                                <table id="datatable" class="table  table-hover table-sm table-bordered p-0"
                                    data-page-length="50" style="text-align: center">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>{{ trans('teacher_trans.teacher_name') }}</th>
                                            <th>{{ trans('teacher_trans.gender') }}</th>
                                            <th>{{ trans('teacher_trans.joining_date') }}</th>
                                            <th>{{ trans('teacher_trans.specialization') }}</th>
                                            <th>{{ trans('teacher_trans.processes') }}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $i = 0; ?>
                                        @foreach ($teachers as $teacher)
                                            <tr>
                                                <?php $i++; ?>
                                                <td>{{ $i }}</td>
                                                <td>{{ $teacher->name }}</td>
                                                <td>{{ $teacher->genders->name }}</td>
                                                <td>{{ $teacher->joining_date }}</td>
                                                <td>{{ $teacher->specializations->name }}</td>
                                                <td>
                                                    <a href="{{ route('teachers.edit', $teacher->id) }}"
                                                        class="btn btn-info btn-sm" role="button" aria-pressed="true"><i
                                                            class="fa fa-edit"></i></a>
                                                    <button type="button" class="btn btn-danger btn-sm"
                                                        data-toggle="modal"
                                                        data-target="#delete_Teacher{{ $teacher->id }}"
                                                        title="{{ trans('grades_trans.delete') }}"><i
                                                            class="fa fa-trash"></i></button>
                                                </td>
                                            </tr>

                                            <div class="modal fade" id="delete_Teacher{{ $teacher->id }}"
                                                tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                                aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <form action="{{ route('teachers.destroy', 'test') }}"
                                                        method="post">
                                                        {{ method_field('delete') }}
                                                        {{ csrf_field() }}
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 style="font-family: 'Cairo', sans-serif;"
                                                                    class="modal-title" id="exampleModalLabel">
                                                                    {{ trans('teacher_trans.delete_teacher') }}</h5>
                                                                <button type="button" class="close"
                                                                    data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p> {{ trans('classrooms_trans.warning_class') }}</p>
                                                                <input type="hidden" name="id"
                                                                    value="{{ $teacher->id }}">
                                                            </div>
                                                            <div class="modal-footer">
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary"
                                                                        data-dismiss="modal">{{ trans('classrooms_trans.close') }}</button>
                                                                    <button type="submit"
                                                                        class="btn btn-danger">{{ trans('classrooms_trans.submit') }}</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- row closed -->
@endsection
@section('js')
@toastr_js
@toastr_render
@endsection