routes/web.php
<?php

namespace App\Http\Controllers\Grade;

namespace App\Http\Controllers;

use App\Http\Controllers\Classroom\ClassroomController;
use App\Http\Controllers\Grade\GradeController;
use App\Http\Controllers\Section\SectionController;
use App\Http\Controllers\Student\AttendanceController;
use App\Http\Controllers\Student\FeeController;
use App\Http\Controllers\Student\FeeInvoiceController;
use App\Http\Controllers\Student\GraduatedController;
use App\Http\Controllers\Student\PaymentStudentController;
use App\Http\Controllers\Student\ProcessingFeeController;
use App\Http\Controllers\Student\PromotionController;
use App\Http\Controllers\Student\ReceiptStudentController;
use App\Http\Controllers\Student\StudentController;
use Facade\FlareClient\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['guest']], function () {
    Route::get('/', function () {
        return view('auth.login');
    });
});




Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'auth']
    ],
    function () {

        // Route::get('/', function () {
        //     return view('dashboard');
        // });
        Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');

        Route::resource('grades', GradeController::class);
        //
        Route::resource('classrooms', ClassroomController::class);
        Route::post('delete_all', [ClassroomController::class, 'delete_all'])->name('delete_all');
        Route::post('filter_classes', [ClassroomController::class, 'filter_classes'])->name('filter_classes');
        //
        Route::resource('sections', SectionController::class);
        Route::get('/classes/{id}', [SectionController::class, 'getclasses']);

        //
        Route::view('add_parent', 'livewire.show_form');

        //
        Route::resource('teachers', TeacherController::class);

        //
        Route::resource('students', StudentController::class);

        Route::get('/get_classrooms/{id}', [StudentController::class, 'get_classrooms']);
        Route::get('/get_sections/{id}', [StudentController::class, 'get_sections']);
        Route::post('upload_attachment', [StudentController::class, 'upload_attachment'])->name('upload_attachment');
        Route::get('download_attachment/{studentName}/{fileName}', [StudentController::class, 'download_attachment'])->name('download_attachment');
        Route::post('delete_attachment', [StudentController::class, 'delete_attachment'])->name('delete_attachment');

        Route::resource('promotions', PromotionController::class);
        Route::resource('graduated', GraduatedController::class);
        Route::resource('fees', FeeController::class);
        Route::resource('fees_invoices', FeeInvoiceController::class);
        Route::resource('receipt_students', ReceiptStudentController::class);
        Route::resource('processing_fees', ProcessingFeeController::class);
        Route::resource('payment_students', PaymentStudentController::class);
        Route::resource('attendance', AttendanceController::class );
        Route::resource('subjects', SubjectController::class);


    }
);

        //...

resources/views/payment/add.blade.php
@extends('layouts.master')
@section('css')
    @toastr_css
@section('title')
    {{ trans('fees_trans.cashing#') }}

@stop
@endsection
@section('page-header')
<!-- breadcrumb -->
@section('PageTitle')
    {{ trans('fees_trans.cashing#') }}
    {{ $student->name }}
@stop
<!-- breadcrumb -->
@endsection
@section('content')
<!-- row -->
<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form method="post" action="{{ route('payment_students.store') }}" autocomplete="off">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{{ trans('fees_trans.amount') }} : <span class="text-danger">*</span></label>
                                <input class="form-control" name="debit" type="number">
                                <input type="hidden" name="student_id" value="{{ $student->id }}"
                                    class="form-control">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{{ trans('fees_trans.student_fee') }} : </label>
                                <input class="form-control" name="final_balance"
                                    value="{{ number_format($student->student_account->sum('debit') - $student->student_account->sum('credit'), 2) }}"
                                    type="text" readonly>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>البيان : <span class="text-danger">*</span></label>
                                <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-success btn-sm nextBtn btn-lg pull-right"
                        type="submit">{{ trans('Students_trans.submit') }}</button>
                </form>

            </div>
        </div>
    </div>
</div>
<!-- row closed -->
@endsection
@section('js')
@toastr_js
@toastr_render

@endsection

resources/views/payment/delete.blade.php
<!-- Deleted inFormation Student -->
<div class="modal fade" id="Delete_receipt{{ $payment_student->id }}" tabindex="-1"
    aria-labelledby="exampleModalLabel" aria-hidden="true">{{ trans('fees_trans.delete_cashing') }}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 style="font-family: 'Cairo', sans-serif;" class="modal-title" id="exampleModalLabel">
                    {{ trans('fees_trans.delete_cashing') }}
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('payment_students.destroy', 'test') }}" method="post">
                    @csrf
                    @method('DELETE')
                    <input type="hidden" name="id" value="{{ $payment_student->id }}">
                    <h5 style="font-family: 'Cairo', sans-serif;">{{ trans('fees_trans.delete_sure') }}</h5>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary"
                            data-dismiss="modal">{{ trans('students_trans.close') }}</button>
                        <button class="btn btn-danger">{{ trans('students_trans.submit') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/payment/edit.blade.php
@extends('layouts.master')
@section('css')
    @toastr_css
@section('title')
    {{ trans('fees_trans.edit_cashing') }}
@stop
@endsection
@section('page-header')
<!-- breadcrumb -->
@section('PageTitle')
    {{ trans('fees_trans.edit_cashing') }}
    : <label style="color: red">{{ $payment_student->student->name }}</label>
@stop
<!-- breadcrumb -->
@endsection
@section('content')
<!-- row -->
<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form action="{{ route('payment_students.update', 'test') }}" method="post" autocomplete="off">
                    @method('PUT')
                    @csrf
                    @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>{{ trans('fees_trans.amount') }} : <span class="text-danger">*</span></label>
                                <input class="form-control" name="debit" value="{{ $payment_student->amount }}"
                                    type="number">
                                <input type="hidden" name="student_id" value="{{ $payment_student->student->id }}"
                                    class="form-control">
                                <input type="hidden" name="id" value="{{ $payment_student->id }}"
                                    class="form-control">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>{{ trans('fees_invoices_trans.statement') }} : <span
                                        class="text-danger">*</span></label>
                                <textarea class="form-control" name="description" id="exampleFormControlTextarea1"
                                    rows="3">{{ $payment_student->description }}</textarea>
                            </div>
                        </div>

                    </div>

                    <button class="btn btn-success btn-sm nextBtn btn-lg pull-right"
                        type="submit">{{ trans('students_trans.submit') }}</button>
                </form>

            </div>
        </div>
    </div>
</div>
<!-- row closed -->
@endsection
@section('js')
@toastr_js
@toastr_render

@endsection

resources/views/payment/index.blade.php
@extends('layouts.master')
@section('css')
    @toastr_css
@section('title')
    {{ trans('fees_trans.cashing#') }}
@stop
@endsection
@section('page-header')
<!-- breadcrumb -->
@section('PageTitle')
    {{ trans('fees_trans.cashing#') }}

@stop
<!-- breadcrumb -->
@endsection
@section('content')
<!-- row -->
<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">
                <div class="col-xl-12 mb-30">
                    <div class="card card-statistics h-100">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="datatable" class="table  table-hover table-sm table-bordered p-0"
                                    data-page-length="50" style="text-align: center">
                                    <thead>
                                        <tr class="alert-success">
                                            <th>#</th>
                                            <th>{{ trans('fees_trans.name') }}</th>

                                            <th>{{ trans('fees_trans.amount') }}</th>

                                            <th>{{ trans('fees_invoices_trans.statement') }}</th>

                                            <th>{{ trans('fees_trans.processes') }}</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($payment_students as $payment_student)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $payment_student->student->name }}</td>
                                                <td>{{ number_format($payment_student->amount, 2) }}</td>
                                                <td>{{ $payment_student->description }}</td>
                                                <td>
                                                    <a href="{{ route('payment_students.edit', $payment_student->id) }}"
                                                        class="btn btn-info btn-sm" role="button" aria-pressed="true"><i
                                                            class="fa fa-edit"></i></a>
                                                    <button type="button" class="btn btn-danger btn-sm"
                                                        data-toggle="modal"
                                                        data-target="#Delete_receipt{{ $payment_student->id }}"><i
                                                            class="fa fa-trash"></i></button>
                                                </td>
                                            </tr>
                                            @include('payment.delete')
                                        @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>x
<!-- row closed -->
@endsection
@section('js')
@toastr_js
@toastr_render
@endsection