routes/web.php
<?php

namespace App\Http\Controllers\Grade;

namespace App\Http\Controllers;

use App\Http\Controllers\Classroom\ClassroomController;
use App\Http\Controllers\Grade\GradeController;
use App\Http\Controllers\Section\SectionController;
use App\Http\Controllers\Student\AttendanceController;
use App\Http\Controllers\Student\FeeController;
use App\Http\Controllers\Student\FeeInvoiceController;
use App\Http\Controllers\Student\GraduatedController;
use App\Http\Controllers\Student\PaymentStudentController;
use App\Http\Controllers\Student\ProcessingFeeController;
use App\Http\Controllers\Student\PromotionController;
use App\Http\Controllers\Student\ReceiptStudentController;
use App\Http\Controllers\Student\StudentController;
use Facade\FlareClient\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['guest']], function () {
    Route::get('/', function () {
        return view('auth.login');
    });
});




Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'auth']
    ],
    function () {

        // Route::get('/', function () {
        //     return view('dashboard');
        // });
        Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');

        Route::resource('grades', GradeController::class);
        //
        Route::resource('classrooms', ClassroomController::class);
        Route::post('delete_all', [ClassroomController::class, 'delete_all'])->name('delete_all');
        Route::post('filter_classes', [ClassroomController::class, 'filter_classes'])->name('filter_classes');
        //
        Route::resource('sections', SectionController::class);
        Route::get('/classes/{id}', [SectionController::class, 'getclasses']);

        //
        Route::view('add_parent', 'livewire.show_form');

        //
        Route::resource('teachers', TeacherController::class);

        //
        Route::resource('students', StudentController::class);

        Route::get('/get_classrooms/{id}', [StudentController::class, 'get_classrooms']);
        Route::get('/get_sections/{id}', [StudentController::class, 'get_sections']);
        Route::post('upload_attachment', [StudentController::class, 'upload_attachment'])->name('upload_attachment');
        Route::get('download_attachment/{studentName}/{fileName}', [StudentController::class, 'download_attachment'])->name('download_attachment');
        Route::post('delete_attachment', [StudentController::class, 'delete_attachment'])->name('delete_attachment');

        Route::resource('promotions', PromotionController::class);
        Route::resource('graduated', GraduatedController::class);
        Route::resource('fees', FeeController::class);
        Route::resource('fees_invoices', FeeInvoiceController::class);
        Route::resource('receipt_students', ReceiptStudentController::class);
        Route::resource('processing_fees', ProcessingFeeController::class);
        Route::resource('payment_students', PaymentStudentController::class);
        Route::resource('attendance', AttendanceController::class );
        Route::resource('subjects', SubjectController::class);


    }
);

        //...

app/Models/Subject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class Subject extends Model
{
    use HasFactory;
    use HasTranslations;

    public $translatable = ['name'];

    protected $fillable = ['name', 'grade_id', 'classroom_id', 'teacher_id'];


    // جلب اسم المراحل الدراسية

    public function grade()
    {
        return $this->belongsTo('App\Models\Grade', 'grade_id');
    }

    // جلب اسم الصفوف الدراسية
    public function classroom()
    {
        return $this->belongsTo('App\Models\Classroom', 'classroom_id');
    }

    // جلب اسم المعلم
    public function teacher()
    {
        return $this->belongsTo('App\Models\Teacher', 'teacher_id');
    }
}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use App\Repository\SubjectRepositoryInterface;
use Illuminate\Http\Request;

class SubjectController extends Controller
{
    protected $subject;

    public function __construct(SubjectRepositoryInterface $subject)
    {
        $this->subject = $subject;
    }
   
    public function index()
    {
        return $this->subject->index();

    }

    
    public function create()
    {
        return $this->subject->create();

    }

   
    public function store(Request $request)
    {
        return $this->subject->store($request);
  
    }

 
    public function show($id)
    {
        
    }

    public function edit($id)
    {
        return $this->subject->edit($id);

        
    }

  
    public function update(Request $request, $id)
    {
        return $this->subject->update($request);

    }

    
    public function destroy(Request $request)
    {
        return $this->subject->destroy($request);

    }
}

resources/views/subjects/create.blade.php
@extends('layouts.master')
@section('css')
    @toastr_css
@section('title')
    {{ trans('subjects_trans.add_a_subject') }}
@stop
@endsection
@section('page-header')
<!-- breadcrumb -->
@section('PageTitle')
    {{ trans('subjects_trans.add_a_subject') }}

@stop
<!-- breadcrumb -->
@endsection
@section('content')
<!-- row -->
<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">

                @if (session()->has('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>{{ session()->get('error') }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
                <div class="col-xs-12">
                    <div class="col-md-12">
                        <br>
                        <form action="{{ route('subjects.store') }}" method="post" autocomplete="off">
                            @csrf

                            <div class="form-row">
                                <div class="col">
                                    <label for="title">{{ trans('subjects_trans.name_of_the_subject_ar') }}</label>
                                    <input type="text" name="name_ar" class="form-control">
                                </div>
                                <div class="col">
                                    <label for="title">{{ trans('subjects_trans.name_of_the_subject_en') }}</label>
                                    <input type="text" name="name_en" class="form-control">
                                </div>
                            </div>
                            <br>

                            <div class="form-row">
                                <div class="form-group col">
                                    <label for="inputState">{{ trans('students_trans.grade') }}</label>
                                    <select class="custom-select my-1 mr-sm-2" name="grade_id">
                                        <option selected disabled>{{ trans('Parent_trans.choose') }}...</option>
                                        @foreach ($grades as $grade)
                                            <option value="{{ $grade->id }}">{{ $grade->name }}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group col">
                                    <label for="inputState">{{ trans('students_trans.classrooms') }}</label>
                                    <select name="class_id" class="custom-select"></select>
                                </div>


                                <div class="form-group col">
                                    <label for="inputState">{{ trans('teacher_trans.teacher_name') }}</label>
                                    <select class="custom-select my-1 mr-sm-2" name="teacher_id">
                                        <option selected disabled>{{ trans('parent_trans.choose') }}...</option>
                                        @foreach ($teachers as $teacher)
                                            <option value="{{ $teacher->id }}">{{ $teacher->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <button class="btn btn-success btn-sm nextBtn btn-lg pull-right" type="submit">
                                {{ trans('students_trans.confirm') }}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- row closed -->
@endsection
@section('js')
@toastr_js
@toastr_render
<script>
    $(document).ready(function() {
        $('select[name="grade_id"]').on('change', function() {
            var grade_id = $(this).val();
            if (grade_id) {
                $.ajax({
                    url: "{{ URL::to('classes') }}/" + grade_id,
                    type: "GET",
                    dataType: "json",
                    success: function(data) {
                        $('select[name="class_id"]').empty();
                        $.each(data, function(key, value) {
                            $('select[name="class_id"]').append('<option value="' +
                                key + '">' + value + '</option>');
                        });
                    },
                });
            } else {
                console.log('AJAX load did not work');
            }
        });
    });
</script>
@endsection

resources/views/subjects/edit.blade.php
@extends('layouts.master')
@section('css')
    @toastr_css
@section('title')
    {{ trans('subjects_trans.add_a_subject') }}
@stop
@endsection
@section('page-header')
<!-- breadcrumb -->
@section('PageTitle')
    {{ trans('subjects_trans.add_a_subject') }}
@stop
<!-- breadcrumb -->
@endsection
@section('content')
<!-- row -->
<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">

                @if (session()->has('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>{{ session()->get('error') }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
                <div class="col-xs-12">
                    <div class="col-md-12">
                        <br>
                        <form action="{{ route('subjects.update', 'test') }}" method="post" autocomplete="off">
                            {{ method_field('patch') }}
                            @csrf
                            <div class="form-row">
                                <div class="col">
                                    <label for="title">{{ trans('subjects_trans.name_of_the_subject_ar') }}</label>
                                    <input type="text" name="name_ar"
                                        value="{{ $subject->getTranslation('name', 'ar') }}" class="form-control">
                                    <input type="hidden" name="id" value="{{ $subject->id }}">
                                </div>
                                <div class="col">
                                    <label for="title">{{ trans('subjects_trans.name_of_the_subject_en') }}</label>
                                    <input type="text" name="name_en"
                                        value="{{ $subject->getTranslation('name', 'en') }}" class="form-control">
                                </div>
                            </div>
                            <br>

                            <div class="form-row">
                                <div class="form-group col">
                                    <label for="inputState">{{ trans('students_trans.grade') }}</label>
                                    <select class="custom-select my-1 mr-sm-2" name="grade_id">
                                        <option selected disabled>{{ trans('Parent_trans.Choose') }}...</option>
                                        @foreach ($grades as $grade)
                                            <option value="{{ $grade->id }}"
                                                {{ $grade->id == $subject->grade_id ? 'selected' : '' }}>
                                                {{ $grade->name }}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group col">
                                    <label for="inputState">{{ trans('students_trans.classrooms') }}</label>
                                    <select name="class_id" class="custom-select">
                                        <option value="{{ $subject->classroom->id }}">
                                            {{ $subject->classroom->name_class }}
                                        </option>
                                    </select>
                                </div>

                                <div class="form-group col">
                                    <label for="inputState">{{ trans('teacher_trans.teacher_name') }}</label>
                                    <select class="custom-select my-1 mr-sm-2" name="teacher_id">
                                        <option selected disabled>{{ trans('parent_trans.choose') }}...</option>
                                        @foreach ($teachers as $teacher)
                                            <option value="{{ $teacher->id }}"
                                                {{ $teacher->id == $subject->teacher_id ? 'selected' : '' }}>
                                                {{ $teacher->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <button class="btn btn-success btn-sm nextBtn btn-lg pull-right" type="submit">
                                {{ trans('students_trans.confirm') }}

                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- row closed -->
@endsection
@section('js')
@toastr_js
@toastr_render
<script>
    $(document).ready(function() {
        $('select[name="grade_id"]').on('change', function() {
            var grade_id = $(this).val();
            if (grade_id) {
                $.ajax({
                    url: "{{ URL::to('classes') }}/" + grade_id,
                    type: "GET",
                    dataType: "json",
                    success: function(data) {
                        $('select[name="class_id"]').empty();
                        $.each(data, function(key, value) {
                            $('select[name="class_id"]').append('<option value="' +
                                key + '">' + value + '</option>');
                        });
                    },
                });
            } else {
                console.log('AJAX load did not work');
            }
        });
    });
</script>
@endsection

resources/views/subjects/index.blade.php
@extends('layouts.master')
@section('css')
    @toastr_css
@section('title')
    {{ trans('subjects_trans.subject_list') }}
@stop
@endsection
@section('page-header')
<!-- breadcrumb -->
@section('PageTitle')
    {{ trans('subjects_trans.subject_list') }}
@stop
<!-- breadcrumb -->
@endsection
@section('content')
<!-- row -->
<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">
                <div class="col-xl-12 mb-30">
                    <div class="card card-statistics h-100">
                        <div class="card-body">
                            <a href="{{ route('subjects.create') }}" class="btn btn-success btn-sm" role="button"
                                aria-pressed="true"> {{ trans('subjects_trans.add_a_subject') }}</a><br><br>
                            <div class="table-responsive">
                                <table id="datatable" class="table  table-hover table-sm table-bordered p-0"
                                    data-page-length="50" style="text-align: center">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>{{ trans('subject_trans.name_of_the_subject') }}</th>
                                            <th>{{ trans('students_trans.grade') }}</th>
                                            <th>{{ trans('students_trans.classrooms') }}</th>
                                            <th>{{ trans('teacher_trans.teacher_name') }}</th>
                                            <th>{{ trans('grades_trans.processes') }}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($subjects as $subject)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $subject->name }}</td>
                                                <td>{{ $subject->grade->name }}</td>
                                                <td>{{ $subject->classroom->name_class }}</td>
                                                <td>{{ $subject->teacher->name }}</td>
                                                <td>
                                                    <a href="{{ route('subjects.edit', $subject->id) }}"
                                                        class="btn btn-info btn-sm" role="button" aria-pressed="true"><i
                                                            class="fa fa-edit"></i></a>
                                                    <button type="button" class="btn btn-danger btn-sm"
                                                        data-toggle="modal"
                                                        data-target="#delete_subject{{ $subject->id }}"
                                                        title="حذف"><i class="fa fa-trash"></i></button>
                                                </td>
                                            </tr>

                                            <div class="modal fade" id="delete_subject{{ $subject->id }}"
                                                tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                                aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <form action="{{ route('subjects.destroy', 'test') }}"
                                                        method="post">
                                                        {{ method_field('delete') }}
                                                        {{ csrf_field() }}
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 style="font-family: 'Cairo', sans-serif;"
                                                                    class="modal-title" id="exampleModalLabel">
                                                                    {{ trans('subjects_trans.delete_subject') }}</h5>
                                                                <button type="button" class="close"
                                                                    data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p> {{ trans('grades_trans.warning_grade') }}
                                                                    {{ $subject->name }}</p>
                                                                <input type="hidden" name="id"
                                                                    value="{{ $subject->id }}">
                                                            </div>
                                                            <div class="modal-footer">
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary"
                                                                        data-dismiss="modal">{{ trans('classrooms_trans.close') }}</button>
                                                                    <button type="submit"
                                                                        class="btn btn-danger">{{ trans('classrooms_trans.submit') }}</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- row closed -->
@endsection
@section('js')
@toastr_js
@toastr_render
@endsection